---
modules-search: [ local ]

instances:
- id:       rootfs
  module:   unpackfs
  config:   unpackfs_rootfs.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs@rootfs
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader-config
  - umount
- show:
  - finished

branding: default

prompt-install: true
dont-chroot: false
